### ISSUE TITLE
markasjunk2_ham_mbox

### ISSUE THREAD

**Issue by rdg050** [JohnDoh/Roundcube-Plugin-Mark-as-Junk-2#36]
Is it possible to have 'ham_mbox'/'spam-mbox' point to more than one mailbox? 
I currently have users move/copy messages to two special mailboxes on their accounts - report-spam/report-ham. Those folders are periodically collected and emptied on the server by a cron job and fed into sa-learn. 
So what I would ideally like to happen is when a user marks a message as SPAM it is moved to the 'junk' folder and a copy is placed in 'report-spam'. And when the user marks a message as HAM it is moved to the 'INBOX' and a copy is placed in 'report-ham'.

**Comment by JohnDoh** [comment]
ham_mbox/spam-mbox cannot be multiple folders but a driver can be used to do what you want, like the dir_learn driver.
