### ISSUE TITLE
amavis_blacklist problem

### ISSUE THREAD

**Issue by gilliattbastos** [JohnDoh/Roundcube-Plugin-Mark-as-Junk-2#37]
Hi, 

I'm trying to use this driver in Roundcube 1.0.1, but the button does not perform any function. When it is active in roundcube is eternally loading.

Can you give any tips to configure it.

Thx

**Comment by JohnDoh** [comment]
this is not a support forum so you might be better off posting to the roundcubeforum but first you said roundcube is eternally loading - in that case there is usually something in the roundcube error log that will tell you what wrong.
