### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Pikeman85** [JohnDoh/Roundcube-Plugin-Mark-as-Junk-2#38]
I am getting Uncaught TypeError: undefined is not a function when running Roundcube with MarkasJunk2.

It seems to happen in rcmail_markasjunk2_update()

and seems to be relating to the following line:

if (rcmail.env.markasjunk2_override || rcmail.is_multifolder_listing()) {

**Comment by JohnDoh** [comment]
looks like a version issue. please ensure you are using the right version of the plugin for your version of Roundcube. https://github.com/JohnDoh/Roundcube-Plugin-Mark-as-Junk-2/releases
