### ISSUE TITLE
Not Junk Button

### ISSUE THREAD

**Issue by rod-jordan** [JohnDoh/Roundcube-Plugin-Mark-as-Junk-2#40]
I have the plugin working somewhat on RC ver. 1.1.3 and 1.0.3. However with either version of RC and different versions of the plugin I never get a "Not Junk" button in any mailbox? I have tried with MS EDGE, Firefox, and Chrome all with same result. I am using uniserver on Windows 10 as the web server.

**Comment by JohnDoh** [comment]
Check this option in your markasjunk2 config file:
```
// Spam mailbox
// Mailbox messages should be moved to when they are marked as spam.
// null = the mailbox assigned as the spam folder in Roundcube settings
// set to FALSE to disable message moving
$config['markasjunk2_spam_mbox'] = null;
```
Note if you have it set to null then you have to check that you have set your spam mailbox in your Roundcube settings.

**Comment by rod-jordan** [comment]
Thanks for the info and also for a great plugin. Now on to configure the
rest of the script to us sa-learn. 

Rod 

On 2015-10-06 03:12, JohnDoh wrote: 

> Check this option in your markasjunk2 config file: 
> 
> // Spam mailbox
> // Mailbox messages should be moved to when they are marked as spam.
> // null = the mailbox assigned as the spam folder in Roundcube settings
> // set to FALSE to disable message moving
> $config['markasjunk2_spam_mbox'] = null;
> 
> Note if you have it set to null then you have to check that you have set your spam mailbox in your Roundcube settings. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/JohnDoh/Roundcube-Plugin-Mark-as-Junk-2/issues/40#issuecomment-145777647
