### ISSUE TITLE
Cannot install MarkAsJunk2

### ISSUE THREAD

**Issue by less0** [JohnDoh/Roundcube-Plugin-Mark-as-Junk-2#49]
With RC 1.2 I have not been able at all to install the plugin. I've tried the installation with plugin manager, as well as manual installation.

In the first case it seems to be installed correctly. I've added the plugin to the composer.json file and installed everything, but the plugin is not loaded. Unfortunately I could not find any error causing this behavior.

When I'm installing the plugin manually (download, add to main.inc.php) RC complains, that the plugin should be loaded via plugin manager and refuses to run at all.

I will happily provide any further information, if that would help.

**Comment by JohnDoh** [comment]
What is plugin manager? I could be that what ever that is is interfering with the normal Roundcube plugin install process that composer uses and that is why the plugin is not activated. Also there is no such file as main.inc.php in Roundcube 1.2.

**Comment by JohnDoh** [comment]
no feedback

**Comment by less0** [comment]
I am sorry that I did not respond. I managed to get it working by re-installing roundcube from scratch.
