### ISSUE TITLE
Option to enable "Not Junk" button not only in folder spam

### ISSUE THREAD

**Issue by chris-asdf** [JohnDoh/Roundcube-Plugin-Mark-as-Junk-2#51]
Hi,

would it be possible to enhance the plugin by a config option containing an array of folders where the "Not Junk" button is shown instead of the "Junk" button.
In my case there are multple spam folders due to different namespaces. But marking mails as ham is only possible in the folder defined in markasjunk2_spam_mbox.

Best Regards
Chris

**Comment by JohnDoh** [comment]
This sounds similar to #50 to me. May be the same trick, using a driver will also work for you?

**Comment by chris-asdf** [comment]
That's exactly what I searched for. Thanks a lot.
Maybe put the jsevent.php from your gist directly in the drivers directory?

Best Regards
Chris
