### ISSUE TITLE
Webmail in a different server

### ISSUE THREAD

**Issue by lpossamai** [JohnDoh/Roundcube-Plugin-Mark-as-Junk-2#52]
Hi,

I got two servers:

mail = postfix + dovecot + spamassassin + clamav + amavisd
www = apache + roundcube(webmail)

When setting up this plugin, I need to edit the file: plugins/markasjunk2/config.inc.php

```
$config['markasjunk2_spam_cmd'] = 'sa-learn --spam --username=vmail %f';
$config['markasjunk2_ham_cmd'] = 'sa-learn --ham --username=vmail %f';
```

Will those commands work? Because I have webmail in a separated machine?

Thanks

**Comment by JohnDoh** [comment]
that would run sa-learn on the webserver.

this is a bug tracker not a support forum. please use http://roundcubeforum.net/
